version: "3.9"
services:

  db:
    image: postgres:12-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - backend/.env
    ports:
      - 5432:5432
    logging:
        driver: none

  backend:  # This service that serves the api for regression and classification
    build: backend
    entrypoint: ./entrypoint.sh
    image: app-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db
      - redis
    stdin_open: true # for testing
    tty: true # for testing
